In [1]:
import pandas as pd
df17 = pd.read_csv('/Users/harrisonchen/Desktop/CCTO Payment/2017.rpt',sep='|',
                   dtype = {'PIN': str, 'Volume': str, 'DatePaid': str, 'SerialNumber':str, 'SourceID':str,})
df18 = pd.read_csv('/Users/harrisonchen/Desktop/CCTO Payment/2018.rpt',sep='|',
                   dtype = {'PIN': str, 'Volume': str, 'DatePaid': str, 'SerialNumber':str, 'SourceID':str,})
df19 = pd.read_csv('/Users/harrisonchen/Desktop/CCTO Payment/2019.rpt',sep='|',
                   dtype = {'PIN': str, 'Volume': str, 'DatePaid': str, 'SerialNumber':str, 'SourceID':str,})
df20 = pd.read_csv('/Users/harrisonchen/Desktop/CCTO Payment/2020.rpt',sep='|',
                   dtype = {'PIN': str, 'Volume': str, 'DatePaid': str, 'SerialNumber':str, 'SourceID':str,})
df21 = pd.read_csv('/Users/harrisonchen/Desktop/CCTO Payment/2021.rpt',sep='|',
                   dtype = {'PIN': str, 'Volume': str, 'DatePaid': str, 'SerialNumber':str, 'SourceID':str,})
y5 = pd.concat([df17,df18,df19,df20,df21])

In [2]:
df17=1
df18=1
df19=1
df20=1
df21=1
y5

,Payment,Volume,PIN,TaxType,TaxPayer,TaxYear,DatePaid,TaxPaid,InterestPaid,CostPaid,SerialNumber,SourceID,DateUpdated,RefundNumber,TotalPaid,TaxYear4,WarrantYear
0,P1,602,00000006021415,9.0,RAILROAD,17.0,180214,7282.52,0.00,0.0,021518300001,501,2018-02-16 05:31:00,NaN,7282.52,2017.0,2017.0
1,P2,602,00000006021415,9.0,RAILROAD,17.0,180724,4191.36,0.00,0.0,072518300008,501,2018-07-26 05:31:00,NaN,4191.36,2017.0,2017.0
2,P1,602,00000006021421,9.0,RAILROAD,17.0,180214,6970.00,0.00,0.0,021518300002,501,2018-02-16 05:31:00,NaN,6970.00,2017.0,2017.0
3,P2,602,00000006021421,9.0,RAILROAD,17.0,180724,4008.41,0.00,0.0,072518300009,501,2018-07-26 05:31:00,NaN,4008.41,2017.0,2017.0
4,P1,602,00000006021436,9.0,RAILROAD,17.0,180214,388701.20,0.00,0.0,021518300003,501,2018-02-16 05:31:00,NaN,388701.20,2017.0,2017.0
5,P2,602,00000006021436,9.0,RAILROAD,17.0,180724,230365.89,0.00,0.0,072518300010,501,2018-07-26 05:31:00,NaN,230365.89,2017.0,2017.0
6,P1,602,00000006021470,9.0,RAILROAD,17.0,180214,40817.71,0.00,0.0,021518300004,501,2018-02-16 05:31:00,NaN,40817.71,2017.0,2017.0
7,P2,602,00000006021470,9.0,RAILROAD,17.0,180724,32332.09,0.00,0.0,072518300011,501,2018-07-26 05:31:00,NaN,32332.09,2017.0,2017.0
8,P1,602,00000006021471,9.0,RAILROAD,17.0,180214,503.49,0.00,0.0,021518300005,501,2018-02-16 05:31:00,NaN,503.49,2017.0,2017.0
9,P2,602,00000006021471,9.0,RAILROAD,17.0,180724,389.22,0.00,0.0,072518300012,501,2018-07-26 05:31:00,NaN,389.22,2017.0,2017.0
10,P1,602,00000006021472,9.0,RAILROAD,17.0,180214,55532.01,0.00,0.0,021518300006,501,2018-02-16 05:31:00,NaN,55532.01,2017.0,2017.0
11,P2,602,00000006021472,9.0,RAILROAD,17.0,180724,42571.87,0.00,0.0,072518300013,501,2018-07-26 05:31:00,NaN,42571.87,2017.0,2017.0
12,P1,602,00000006021477,9.0,RAILROAD,17.0,180214,15654.75,0.00,0.0,021518300007,501,2018-02-16 05:31:00,NaN,15654.75,2017.0,2017.0
13,P2,602,00000006021477,9.0,RAILROAD,17.0,180724,12101.37,0.00,0.0,072518300014,501,2018-07-26 05:31:00,NaN,12101.37,2017.0,2017.0
14,P1,602,00000006021737,9.0,RAILROAD,17.0,180801,17880.20,1341.00,0.0,080218710823,444,2018-08-03 05:31:00,NaN,19221.20,2017.0,2017.0
15,P2,602,00000006021737,9.0,RAILROAD,17.0,180801,13670.48,0.00,0.0,080218710823,444,2018-08-03 05:31:00,NaN,13670.48,2017.0,2017.0
16,P1,602,00000006021770,9.0,RAILROAD,17.0,180801,13715.50,1028.65,0.0,080218710824,444,2018-08-03 05:31:00,NaN,14744.15,2017.0,2017.0
17,P2,602,00000006021770,9.0,RAILROAD,17.0,180801,12346.19,0.00,0.0,080218710824,444,2018-08-03 05:31:00,NaN,12346.19,2017.0,2017.0
18,P1,602,00000006022112,9.0,RAILROAD,17.0,180719,4752.35,356.45,0.0,071918300003,501,2018-07-20 05:31:00,NaN,5108.80,2017.0,2017.0
19,P1,602,00000006022112,9.0,RAILROAD,17.0,190301,0.02,0.00,0.0,030119300001,501,2019-03-02 05:31:00,NaN,0.02,2017.0,2017.0
20,P2,602,00000006022112,9.0,RAILROAD,17.0,190301,2828.34,297.01,0.0,030119300001,501,2019-03-02 05:31:00,NaN,3125.35,2017.0,2017.0
21,P1,602,00000006022113,9.0,RAILROAD,17.0,180719,9983.25,748.75,0.0,071918300004,501,2018-07-20 05:31:00,NaN,10732.00,2017.0,2017.0
22,P1,602,00000006022113,9.0,RAILROAD,17.0,190301,0.01,0.00,0.0,030519300001,501,2019-03-06 05:31:00,NaN,0.01,2017.0,2017.0
23,P2,602,00000006022113,9.0,RAILROAD,17.0,190301,5845.01,613.76,0.0,030519300001,501,2019-03-06 05:31:00,NaN,6458.77,2017.0,2017.0
24,P1,602,00000006022114,9.0,RAILROAD,17.0,180719,218931.14,16419.85,0.0,071918300005,501,2018-07-20 05:31:00,NaN,235350.99,2017.0,2017.0
25,P1,602,00000006022114,9.0,RAILROAD,17.0,190301,0.01,0.00,0.0,030119300002,501,2019-03-02 05:31:00,NaN,0.01,2017.0,2017.0
26,P2,602,00000006022114,9.0,RAILROAD,17.0,190301,140652.98,14768.53,0.0,030119300002,501,2019-03-02 05:31:00,NaN,155421.51,2017.0,2017.0
27,P1,602,00000006022115,9.0,RAILROAD,17.0,180719,80.04,6.00,0.0,071918300006,501,2018-07-20 05:31:00,NaN,86.04,2017.0,2017.0
28,P2,602,00000006022115,9.0,RAILROAD,17.0,190301,51.24,5.39,0.0,030219300001,501,2019-03-03 05:31:00,NaN,56.63,2017.0,2017.0
29,P1,602,00000006022121,9.0,RAILROAD,17.0,180719,64673.04,4850.50,0.0,071918300007,501,2018-07-20 05:31:00,NaN,69523.54,2017.0,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3341188,P1,022,33314020200000,0.0,DAVID M CUNNINGHAM,21.0,220224,215.87,0.00,0.0,022822519067,700,2022-03-01 05:31:00,NaN,215.87,2021.0,2021.0
3341189,P2,022,33314020200000,0.0,DAVID M CUNNINGHAM,21.0,230325,198.44,8.94,0.0,032623500051,750,2023-03-27 05:30:00,NaN,207.38,2021.0,2021.0
3341190,P1,022,33314020220000,0.0,DAVID M CUNNINGHAM,21.0,220224,1171.35,0.00,0.0,022822519068,700,2022-03-01 05:31:00,NaN,1171.35,2021.0,2021.0
3341191,P2,022,33314020220000,0.0,DAVID M CUNNINGHAM,21.0,230325,1295.31,204.69,0.0,032823500713,700,2023-03-29 05:31:00,NaN,1500.00,2021.0,2021.0
3341192,P2,022,33314020220000,0.0,DAVID M CUNNINGHAM,21.0,230331,3253.46,0.00,0.0,040323500687,700,2023-04-04 08:23:00,NaN,3253.46,2021.0,2021.0
3341193,P1,022,33323020030000,0.0,ELSIE M BENIAC,21.0,220213,826.20,0.00,0.0,021322712545,431,2022-02-14 05:31:00,NaN,826.20,2021.0,2021.0
3341194,P2,022,33323020030000,0.0,ELSIE M BENIAC,21.0,221211,875.89,0.00,0.0,121122707981,436,2022-12-12 05:31:00,NaN,875.89,2021.0,2021.0
3341195,P1,022,33323020050000,0.0,NICHOLAS E ARROYO JR,21.0,220224,1718.28,0.00,0.0,022522237669,600,2022-02-26 05:31:00,NaN,1718.28,2021.0,2021.0
3341196,P2,022,33323020050000,0.0,NICHOLAS E ARROYO JR,21.0,221228,2759.55,0.00,0.0,122922255624,600,2022-12-30 05:38:00,NaN,2759.55,2021.0,2021.0
3341197,P1,022,33323020060000,0.0,CLIFFORD J GAWLINSKI &,21.0,220224,4385.08,0.00,0.0,022522237670,600,2022-02-26 05:31:00,NaN,4385.08,2021.0,2021.0
3341198,P2,022,33323020060000,0.0,CLIFFORD J GAWLINSKI &,21.0,221228,1324.91,0.00,0.0,122922255625,600,2022-12-30 05:38:00,NaN,1324.91,2021.0,2021.0
3341199,P1,022,33323020070000,0.0,JOHN S SARROS,21.0,220215,4164.42,0.00,0.0,021622712895,444,2022-02-17 05:31:00,NaN,4164.42,2021.0,2021.0
3341200,P2,022,33323020070000,0.0,JOHN S SARROS,21.0,221212,3671.34,0.00,0.0,121322715733,444,2022-12-14 05:31:00,NaN,3671.34,2021.0,2021.0
3341201,P1,022,33323020090000,0.0,DONALD KONG,21.0,220224,2870.87,0.00,0.0,022522237671,600,2022-02-26 05:31:00,NaN,2870.87,2021.0,2021.0
3341202,P2,022,33323020090000,0.0,DONALD KONG,21.0,221228,2551.76,0.00,0.0,123022259223,600,2022-12-31 05:31:00,NaN,2551.76,2021.0,2021.0
3341203,P1,022,33323020100000,0.0,NOELLE FOLDEN,21.0,220224,3095.71,0.00,0.0,022522237672,600,2022-02-26 05:31:00,NaN,3095.71,2021.0,2021.0
3341204,P2,022,33323020100000,0.0,TAIWUAN B SMITH,21.0,221228,2758.46,0.00,0.0,123122062903,600,2023-01-01 05:32:00,NaN,2758.46,2021.0,2021.0
3341205,P1,022,33323020110000,0.0,JUNE HANSEN,21.0,220301,5267.07,0.00,0.0,030622702199,431,2022-03-07 05:31:00,NaN,5267.07,2021.0,2021.0
3341206,P2,022,33323020110000,0.0,JUNE HANSEN,21.0,221218,4754.01,0.00,0.0,121822703437,436,2022-12-19 05:31:00,NaN,4754.01,2021.0,2021.0
3341207,P1,022,33323020120000,0.0,ELSIE M BENIAC,21.0,220212,295.21,0.00,0.0,021222704352,431,2022-02-13 05:31:00,NaN,295.21,2021.0,2021.0
3341208,P2,022,33323020120000,0.0,ELSIE M BENIAC,21.0,221212,271.27,0.00,0.0,121222705858,436,2022-12-13 05:31:00,NaN,271.27,2021.0,2021.0
3341209,P1,022,33323020130000,0.0,SHERILYN C HAMILTON,21.0,220224,3399.78,0.00,0.0,022622259499,600,2022-02-27 05:32:00,NaN,3399.78,2021.0,2021.0
3341210,P2,022,33323020130000,0.0,SHERILYN C HAMILTON,21.0,221228,3037.97,0.00,0.0,123022259224,600,2022-12-31 05:31:00,NaN,3037.97,2021.0,2021.0
3341211,P1,022,33323020140000,0.0,JENCELYN JOSH WITZEL,21.0,220917,822.27,177.73,0.0,092022500209,700,2022-09-21 05:31:00,NaN,1000.00,2021.0,2021.0
3341212,P1,022,33323020140000,0.0,JENCELYN JOSH WITZEL,21.0,230403,870.55,91.42,0.0,040323500808,750,2023-04-04 08:23:00,NaN,961.97,2021.0,2021.0
3341213,P2,022,33323020140000,0.0,JENCELYN JOSH WITZEL,21.0,230615,1555.77,140.04,0.0,061623500083,700,2023-06-17 05:31:00,NaN,1695.81,2021.0,2021.0
3341214,P1,022,33323020150000,0.0,GARY J ECKERT,21.0,220217,2710.78,0.00,0.0,021922111092,600,2022-02-20 05:32:00,NaN,2710.78,2021.0,2021.0
3341215,P2,022,33323020150000,0.0,GARY J ECKERT,21.0,221220,2491.40,0.00,0.0,122122080500,600,2022-12-22 05:31:00,NaN,2491.40,2021.0,2021.0
3341216,(3341216 rows affected),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3341217,Completion time: 2023-06-29T09:56:41.4645129-0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
y5 = y5.drop(['RefundNumber'],axis=1)
y5 = y5.dropna()
y5

,Payment,Volume,PIN,TaxType,TaxPayer,TaxYear,DatePaid,TaxPaid,InterestPaid,CostPaid,SerialNumber,SourceID,DateUpdated,TotalPaid,TaxYear4,WarrantYear
0,P1,602,00000006021415,9.0,RAILROAD,17.0,180214,7282.52,0.00,0.0,021518300001,501,2018-02-16 05:31:00,7282.52,2017.0,2017.0
1,P2,602,00000006021415,9.0,RAILROAD,17.0,180724,4191.36,0.00,0.0,072518300008,501,2018-07-26 05:31:00,4191.36,2017.0,2017.0
2,P1,602,00000006021421,9.0,RAILROAD,17.0,180214,6970.00,0.00,0.0,021518300002,501,2018-02-16 05:31:00,6970.00,2017.0,2017.0
3,P2,602,00000006021421,9.0,RAILROAD,17.0,180724,4008.41,0.00,0.0,072518300009,501,2018-07-26 05:31:00,4008.41,2017.0,2017.0
4,P1,602,00000006021436,9.0,RAILROAD,17.0,180214,388701.20,0.00,0.0,021518300003,501,2018-02-16 05:31:00,388701.20,2017.0,2017.0
5,P2,602,00000006021436,9.0,RAILROAD,17.0,180724,230365.89,0.00,0.0,072518300010,501,2018-07-26 05:31:00,230365.89,2017.0,2017.0
6,P1,602,00000006021470,9.0,RAILROAD,17.0,180214,40817.71,0.00,0.0,021518300004,501,2018-02-16 05:31:00,40817.71,2017.0,2017.0
7,P2,602,00000006021470,9.0,RAILROAD,17.0,180724,32332.09,0.00,0.0,072518300011,501,2018-07-26 05:31:00,32332.09,2017.0,2017.0
8,P1,602,00000006021471,9.0,RAILROAD,17.0,180214,503.49,0.00,0.0,021518300005,501,2018-02-16 05:31:00,503.49,2017.0,2017.0
9,P2,602,00000006021471,9.0,RAILROAD,17.0,180724,389.22,0.00,0.0,072518300012,501,2018-07-26 05:31:00,389.22,2017.0,2017.0
10,P1,602,00000006021472,9.0,RAILROAD,17.0,180214,55532.01,0.00,0.0,021518300006,501,2018-02-16 05:31:00,55532.01,2017.0,2017.0
11,P2,602,00000006021472,9.0,RAILROAD,17.0,180724,42571.87,0.00,0.0,072518300013,501,2018-07-26 05:31:00,42571.87,2017.0,2017.0
12,P1,602,00000006021477,9.0,RAILROAD,17.0,180214,15654.75,0.00,0.0,021518300007,501,2018-02-16 05:31:00,15654.75,2017.0,2017.0
13,P2,602,00000006021477,9.0,RAILROAD,17.0,180724,12101.37,0.00,0.0,072518300014,501,2018-07-26 05:31:00,12101.37,2017.0,2017.0
14,P1,602,00000006021737,9.0,RAILROAD,17.0,180801,17880.20,1341.00,0.0,080218710823,444,2018-08-03 05:31:00,19221.20,2017.0,2017.0
15,P2,602,00000006021737,9.0,RAILROAD,17.0,180801,13670.48,0.00,0.0,080218710823,444,2018-08-03 05:31:00,13670.48,2017.0,2017.0
16,P1,602,00000006021770,9.0,RAILROAD,17.0,180801,13715.50,1028.65,0.0,080218710824,444,2018-08-03 05:31:00,14744.15,2017.0,2017.0
17,P2,602,00000006021770,9.0,RAILROAD,17.0,180801,12346.19,0.00,0.0,080218710824,444,2018-08-03 05:31:00,12346.19,2017.0,2017.0
18,P1,602,00000006022112,9.0,RAILROAD,17.0,180719,4752.35,356.45,0.0,071918300003,501,2018-07-20 05:31:00,5108.80,2017.0,2017.0
19,P1,602,00000006022112,9.0,RAILROAD,17.0,190301,0.02,0.00,0.0,030119300001,501,2019-03-02 05:31:00,0.02,2017.0,2017.0
20,P2,602,00000006022112,9.0,RAILROAD,17.0,190301,2828.34,297.01,0.0,030119300001,501,2019-03-02 05:31:00,3125.35,2017.0,2017.0
21,P1,602,00000006022113,9.0,RAILROAD,17.0,180719,9983.25,748.75,0.0,071918300004,501,2018-07-20 05:31:00,10732.00,2017.0,2017.0
22,P1,602,00000006022113,9.0,RAILROAD,17.0,190301,0.01,0.00,0.0,030519300001,501,2019-03-06 05:31:00,0.01,2017.0,2017.0
23,P2,602,00000006022113,9.0,RAILROAD,17.0,190301,5845.01,613.76,0.0,030519300001,501,2019-03-06 05:31:00,6458.77,2017.0,2017.0
24,P1,602,00000006022114,9.0,RAILROAD,17.0,180719,218931.14,16419.85,0.0,071918300005,501,2018-07-20 05:31:00,235350.99,2017.0,2017.0
25,P1,602,00000006022114,9.0,RAILROAD,17.0,190301,0.01,0.00,0.0,030119300002,501,2019-03-02 05:31:00,0.01,2017.0,2017.0
26,P2,602,00000006022114,9.0,RAILROAD,17.0,190301,140652.98,14768.53,0.0,030119300002,501,2019-03-02 05:31:00,155421.51,2017.0,2017.0
27,P1,602,00000006022115,9.0,RAILROAD,17.0,180719,80.04,6.00,0.0,071918300006,501,2018-07-20 05:31:00,86.04,2017.0,2017.0
28,P2,602,00000006022115,9.0,RAILROAD,17.0,190301,51.24,5.39,0.0,030219300001,501,2019-03-03 05:31:00,56.63,2017.0,2017.0
29,P1,602,00000006022121,9.0,RAILROAD,17.0,180719,64673.04,4850.50,0.0,071918300007,501,2018-07-20 05:31:00,69523.54,2017.0,2017.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3341186,P1,022,33314020180000,0.0,RUSSEL C REICHERT,21.0,220210,3900.95,0.00,0.0,021122705898,444,2022-02-12 05:31:00,3900.95,2021.0,2021.0
3341187,P2,022,33314020180000,0.0,RUSSEL C REICHERT,21.0,221220,4135.50,0.00,0.0,122122711775,444,2022-12-22 05:31:00,4135.50,2021.0,2021.0
3341188,P1,022,33314020200000,0.0,DAVID M CUNNINGHAM,21.0,220224,215.87,0.00,0.0,022822519067,700,2022-03-01 05:31:00,215.87,2021.0,2021.0
3341189,P2,022,33314020200000,0.0,DAVID M CUNNINGHAM,21.0,230325,198.44,8.94,0.0,032623500051,750,2023-03-27 05:30:00,207.38,2021.0,2021.0
3341190,P1,022,33314020220000,0.0,DAVID M CUNNINGHAM,21.0,220224,1171.35,0.00,0.0,022822519068,700,2022-03-01 05:31:00,1171.35,2021.0,2021.0
3341191,P2,022,33314020220000,0.0,DAVID M CUNNINGHAM,21.0,230325,1295.31,204.69,0.0,032823500713,700,2023-03-29 05:31:00,1500.00,2021.0,2021.0
3341192,P2,022,33314020220000,0.0,DAVID M CUNNINGHAM,21.0,230331,3253.46,0.00,0.0,040323500687,700,2023-04-04 08:23:00,3253.46,2021.0,2021.0
3341193,P1,022,33323020030000,0.0,ELSIE M BENIAC,21.0,220213,826.20,0.00,0.0,021322712545,431,2022-02-14 05:31:00,826.20,2021.0,2021.0
3341194,P2,022,33323020030000,0.0,ELSIE M BENIAC,21.0,221211,875.89,0.00,0.0,121122707981,436,2022-12-12 05:31:00,875.89,2021.0,2021.0
3341195,P1,022,33323020050000,0.0,NICHOLAS E ARROYO JR,21.0,220224,1718.28,0.00,0.0,022522237669,600,2022-02-26 05:31:00,1718.28,2021.0,2021.0
3341196,P2,022,33323020050000,0.0,NICHOLAS E ARROYO JR,21.0,221228,2759.55,0.00,0.0,122922255624,600,2022-12-30 05:38:00,2759.55,2021.0,2021.0
3341197,P1,022,33323020060000,0.0,CLIFFORD J GAWLINSKI &,21.0,220224,4385.08,0.00,0.0,022522237670,600,2022-02-26 05:31:00,4385.08,2021.0,2021.0
3341198,P2,022,33323020060000,0.0,CLIFFORD J GAWLINSKI &,21.0,221228,1324.91,0.00,0.0,122922255625,600,2022-12-30 05:38:00,1324.91,2021.0,2021.0
3341199,P1,022,33323020070000,0.0,JOHN S SARROS,21.0,220215,4164.42,0.00,0.0,021622712895,444,2022-02-17 05:31:00,4164.42,2021.0,2021.0
3341200,P2,022,33323020070000,0.0,JOHN S SARROS,21.0,221212,3671.34,0.00,0.0,121322715733,444,2022-12-14 05:31:00,3671.34,2021.0,2021.0
3341201,P1,022,33323020090000,0.0,DONALD KONG,21.0,220224,2870.87,0.00,0.0,022522237671,600,2022-02-26 05:31:00,2870.87,2021.0,2021.0
3341202,P2,022,33323020090000,0.0,DONALD KONG,21.0,221228,2551.76,0.00,0.0,123022259223,600,2022-12-31 05:31:00,2551.76,2021.0,2021.0
3341203,P1,022,33323020100000,0.0,NOELLE FOLDEN,21.0,220224,3095.71,0.00,0.0,022522237672,600,2022-02-26 05:31:00,3095.71,2021.0,2021.0
3341204,P2,022,33323020100000,0.0,TAIWUAN B SMITH,21.0,221228,2758.46,0.00,0.0,123122062903,600,2023-01-01 05:32:00,2758.46,2021.0,2021.0
3341205,P1,022,33323020110000,0.0,JUNE HANSEN,21.0,220301,5267.07,0.00,0.0,030622702199,431,2022-03-07 05:31:00,5267.07,2021.0,2021.0
3341206,P2,022,33323020110000,0.0,JUNE HANSEN,21.0,221218,4754.01,0.00,0.0,121822703437,436,2022-12-19 05:31:00,4754.01,2021.0,2021.0
3341207,P1,022,33323020120000,0.0,ELSIE M BENIAC,21.0,220212,295.21,0.00,0.0,021222704352,431,2022-02-13 05:31:00,295.21,2021.0,2021.0
3341208,P2,022,33323020120000,0.0,ELSIE M BENIAC,21.0,221212,271.27,0.00,0.0,121222705858,436,2022-12-13 05:31:00,271.27,2021.0,2021.0
3341209,P1,022,33323020130000,0.0,SHERILYN C HAMILTON,21.0,220224,3399.78,0.00,0.0,022622259499,600,2022-02-27 05:32:00,3399.78,2021.0,2021.0
3341210,P2,022,33323020130000,0.0,SHERILYN C HAMILTON,21.0,221228,3037.97,0.00,0.0,123022259224,600,2022-12-31 05:31:00,3037.97,2021.0,2021.0
3341211,P1,022,33323020140000,0.0,JENCELYN JOSH WITZEL,21.0,220917,822.27,177.73,0.0,092022500209,700,2022-09-21 05:31:00,1000.00,2021.0,2021.0
3341212,P1,022,33323020140000,0.0,JENCELYN JOSH WITZEL,21.0,230403,870.55,91.42,0.0,040323500808,750,2023-04-04 08:23:00,961.97,2021.0,2021.0
3341213,P2,022,33323020140000,0.0,JENCELYN JOSH WITZEL,21.0,230615,1555.77,140.04,0.0,061623500083,700,2023-06-17 05:31:00,1695.81,2021.0,2021.0
3341214,P1,022,33323020150000,0.0,GARY J ECKERT,21.0,220217,2710.78,0.00,0.0,021922111092,600,2022-02-20 05:32:00,2710.78,2021.0,2021.0
3341215,P2,022,33323020150000,0.0,GARY J ECKERT,21.0,221220,2491.40,0.00,0.0,122122080500,600,2022-12-22 05:31:00,2491.40,2021.0,2021.0

In [7]:
p1p2 = y5[(y5['Payment'] == 'P1') | (y5['Payment'] == 'P2')]
nop1p2 = y5[(y5['Payment'] != 'P1') & (y5['Payment'] != 'P2')]

In [8]:
nop1p2['PIN'].nunique()

38477

In [10]:
nop1p2[~nop1p2['PIN'].isin(p1p2['PIN'])]['PIN'].nunique()

1589